### ISSUE TITLE
Sample needed

### ISSUE THREAD

**Issue by rofiqsetiawan** [NAXAM/retrofit2-android-binding#1]
Hi, is there any sample how to use this library on Xamarin.Android?

I'm stuck when using IUserAPIService.
Retrofit need it must be an `interface` but also inheritanced from java's object.

```csharp
public interface IUserAPIService
{
	[GET(Value = "api")]
	ICall ResultInfo { get; }
}
```

```csharp
var retrofit = new Retrofit.Builder()
						   .BaseUrl("http://api.blabla.com")
						   .AddConverterFactory(GsonConverterFactory.Create())
						   .Build();


var apiService = retrofit.Create(Java.Lang.Class.FromType(typeof(IUserAPIService)).Class).JavaCast<IUserAPIService>();
```

Thanks.

**Comment by tuyen-vuduc** [comment]
Why do you need to use this library in Xamarin.Android?

No matter your answer is, it's much easier and more re-usable to use HttpClient and RestSharp PCL.
I don't recommend to use this library in Xamarn.Android.

This library was created because it's a dependency for another library. There will be no sample for it.

Cheers.
